WARNING:__main__:Error processing city Lahore: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Chennai: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Gaborone: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Banjul: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Dushanbe: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Auckland: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Nakhon Ratchasima: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Saint-Denis: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Maracaibo: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Linz: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Hanga Roa: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Makati City: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Rockhampton: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Phoenix: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Vancouver: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Iloilo City: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Baku: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Wonsan: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Managua: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
WARNING:__main__:Error processing city Fukuoka: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
ERROR:__main__:Batch processing error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uq_city_name"
DETAIL:  Key (name)=(İzmir) already exists.
[SQL: INSERT INTO cities (name, country_code) VALUES ($1::VARCHAR, $2::VARCHAR) RETURNING cities.id, cities.created_at, cities.updated_at]
[parameters: ('İzmir', 'CA')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
INFO:__main__:🎉 CSV data loading completed!
INFO:__main__:📊 Final Statistics:
INFO:__main__:   - Total rows in CSV: 10000
INFO:__main__:   - Successfully processed: 9961
INFO:__main__:   - Cities created: 652
INFO:__main__:   - Cities updated: 2339
INFO:__main__:   - Rows skipped: 39
INFO:__main__:   - Processing time: 4.16s
WARNING:__main__:⚠️  46 errors occurred during processing
WARNING:__main__:   - Showing first 5 errors:
WARNING:__main__:   - Row 37: Row validation error: Country code is empty
WARNING:__main__:   - Row 1010: Row validation error: Country code is empty
WARNING:__main__:   - Row 1084: Row validation error: Country code is empty
WARNING:__main__:   - Row 1086: Row validation error: Country code is empty
WARNING:__main__:   - Row 1087: Row validation error: Country code is empty
WARNING:__main__:   - ... and 41 more
WARNING:__main__:⚠️  Completed with errors
[ERROR] Data loading script failed. Please check the output above.
